/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type createdStartup = ContractEventLog<{
  startupId: string;
  startUp: [string, string, string, string, string];
  0: string;
  1: [string, string, string, string, string];
}>;

export interface Startup extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Startup;
  clone(): Startup;
  methods: {
    getStartup(
      id: string
    ): NonPayableTransactionObject<{
      name: string;
      categoryId: string;
      mission: string;
      descriptionAddr: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    newStartup(
      p: [string, string, string, string, string]
    ): PayableTransactionObject<void>;

    setCoinBase(addr: string): NonPayableTransactionObject<void>;
  };
  events: {
    createdStartup(cb?: Callback<createdStartup>): EventEmitter;
    createdStartup(
      options?: EventOptions,
      cb?: Callback<createdStartup>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "createdStartup", cb: Callback<createdStartup>): void;
  once(
    event: "createdStartup",
    options: EventOptions,
    cb: Callback<createdStartup>
  ): void;
}
